[package]
name = "envhub-tui"
version.workspace = true
edition.workspace = true

[dependencies]
envhub-core.workspace = true
serde.workspace = true
ratatui = "0.28"
crossterm = "0.27"

[dev-dependencies]
indexmap.workspace = true
