[package]
name = "envhub-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
envhub-core.workspace = true
serde.workspace = true
ratatui = "0.28"
crossterm = "0.27"

[dev-dependencies]
indexmap.workspace = true
